### ISSUE TITLE
Failed to install libraries from requirement files

### ISSUE THREAD

**Issue by amir1189** [sanketsaurav/pnrapi#2]
I am using this pip install -r requirements.txt but it shows lots of error
ERROR: Command errored out with exit status 1:
     command: 'c:\users\amir abbas\appdata\local\programs\python\python36\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\AMIRAB~1\\AppData\\Local\\Temp\\pip-install-rlz9tgj4\\BeautifulSoup\\setup.py'"'"'; __file__='"'"'C:\\Users\\AMIRAB~1\\AppData\\Local\\Temp\\pip-install-rlz9tgj4\\BeautifulSoup\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\AMIRAB~1\AppData\Local\Temp\pip-install-rlz9tgj4\BeautifulSoup\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AMIRAB~1\AppData\Local\Temp\pip-install-rlz9tgj4\BeautifulSoup\setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unit tests have failed!")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by DevParapalli** [comment]
This application runs on python 2.7, You are installing it and its dependencies on 3.6. BeautifulSoup package is deprecated. Please install and try this on python-2.7
